import { NextResponse } from 'next/server'
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require('pdfkit')

export async function POST(req: Request) {
  try {
    const { name, phone, area, urgency, prompt, result } = await req.json()

    const doc = new PDFDocument({ margin: 40 })
    const chunks: Buffer[] = []

    doc.on('data', (c) => chunks.push(c))
    const done = new Promise<Buffer>((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(chunks)))
    })

    doc.fontSize(20).text('ARX Home AI - Diagnosis Report', { underline: true })
    doc.moveDown(0.7)

    doc.fontSize(12).text(`Name: ${name || '-'}`)
    doc.text(`Phone: ${phone || '-'}`)
    doc.text(`Area: ${area || '-'}`)
    doc.text(`Urgency: ${urgency || '-'}`)
    doc.moveDown()

    doc.fontSize(14).text('Problem', { underline: true })
    doc.fontSize(11).text(prompt || '-')
    doc.moveDown()

    doc.fontSize(14).text('AI Diagnosis', { underline: true })
    doc.fontSize(11).text(result || '-')
    doc.moveDown()

    doc.fontSize(10).fillColor('gray').text('Generated by ARX Home AI', { align: 'right' })

    doc.end()
    const pdf = await done

    return new NextResponse(pdf, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename="arx-diagnosis.pdf"',
      },
    })
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'PDF error' }, { status: 500 })
  }
}